name: StyleCop Analysis for C# Code Quality

on:
  push:
    paths:
      - '**/*.cs'
  pull_request:
    paths:
      - '**/*.cs'
  workflow_dispatch:
    inputs:
      custom_username:
        description: 'Enter custom username (default is "default-user")'
        required: false
        default: 'default-user'
      project_id:
        description: 'Enter project ID (default is "default-project")'
        required: false
        default: 'default-project'

jobs:
  analyze:
    name: Run StyleCop Analysis and Generate Report
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x' # Use .NET 8 or 7 for latest projects

    - name: Restore Dependencies
      run: |
        PROJECT=$(find . -name "*.csproj" | head -n 1)
        dotnet restore "$PROJECT"

    - name: Install StyleCop.Analyzers
      run: |
        PROJECT=$(find . -name "*.csproj" | head -n 1)
        dotnet add "$PROJECT" package StyleCop.Analyzers

    - name: Generate StyleCop Report (HTML)
      run: |
        PROJECT=$(find . -name "*.csproj" | head -n 1)
        dotnet build "$PROJECT" -warnaserror --configuration Release

    - name: Extract StyleCop Violations
      id: violations
      run: |
        STYLECOP_WARNINGS=$(grep -E "(SA[0-9]{4})" build-output.txt | wc -l)
        echo "StyleCop Violations: $STYLECOP_WARNINGS"
        echo "stylecop_violations=$STYLECOP_WARNINGS" >> $GITHUB_ENV

    - name: Save Report to docs/ Folder
      run: |
        USERNAME="${{ github.event.inputs.custom_username || 'default-user' }}"
        PROJECT_ID="${{ github.event.inputs.project_id || 'default-project' }}"
        DOCS_FOLDER="docs/${USERNAME}/${PROJECT_ID}/code_quality"
        mkdir -p "$DOCS_FOLDER"
        mv stylecop-report.html "$DOCS_FOLDER/"

    - name: Upload Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: stylecop-report
        path: docs/${{ github.event.inputs.custom_username || 'default-user' }}/**/stylecop-report.html
