name: StyleCop Analysis for C# Code Quality

on:
  push:
    paths:
      - '**/*.cs'
  pull_request:
    paths:
      - '**/*.cs'
  workflow_dispatch:
    inputs:
      custom_username:
        description: 'Enter custom username (default is "default-user")'
        required: false
        default: 'default-user'
      project_id:
        description: 'Enter project ID (default is "default-project")'
        required: false
        default: 'default-project'

jobs: 
  analyze:
    name: Run StyleCop Analysis and Generate Report
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0'  # Use .NET 9.0 for the latest SDK (ensure it's installed)

    - name: Restore Dependencies
      run: |
        PROJECT=$(find . -name "*.csproj" | head -n 1)
        echo "Restoring dependencies for project: $PROJECT"
        dotnet restore "$PROJECT"

    - name: Install StyleCop.Analyzers
      run: |
        PROJECT=$(find . -name "*.csproj" | head -n 1)
        echo "Adding StyleCop.Analyzers to project: $PROJECT"
        dotnet add "$PROJECT" package StyleCop.Analyzers

    - name: Generate StyleCop Report (HTML)
      run: |
        PROJECT=$(find . -name "*.csproj" | head -n 1)
        echo "Building project: $PROJECT"
        
        # Run the build command and capture both stdout and stderr
        dotnet build "$PROJECT" -warnaserror --configuration Release --no-restore /p:NoWarn=NU1902;NU1903 > build-output.txt 2>&1
        
        # Check if the build failed and print the error message
        if [ $? -ne 0 ]; then
          echo "Build failed. See below for error details:"
          cat build-output.txt
          exit 1
        fi

        # If the build is successful, proceed to generate the report
        echo "Build succeeded. Generating StyleCop report..."
        
        # Your further steps to generate the report can go here (e.g., using MSBuild or generating an HTML report)

    - name: Extract StyleCop Violations
      id: violations
      run: |
        # Assuming the build output is redirected to a file (e.g., build-output.txt)
        STYLECOP_WARNINGS=$(grep -E "(SA[0-9]{4})" build-output.txt | wc -l)
        echo "StyleCop Violations: $STYLECOP_WARNINGS"
        echo "stylecop_violations=$STYLECOP_WARNINGS" >> $GITHUB_ENV

    - name: Save Report to docs/ Folder
      run: |
        USERNAME="${{ github.event.inputs.custom_username || 'default-user' }}"
        PROJECT_ID="${{ github.event.inputs.project_id || 'default-project' }}"
        DOCS_FOLDER="docs/${USERNAME}/${PROJECT_ID}/code_quality"
        mkdir -p "$DOCS_FOLDER"
        mv stylecop-report.html "$DOCS_FOLDER/"

    - name: Upload Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: stylecop-report
        path: docs/${{ github.event.inputs.custom_username || 'default-user' }}/**/stylecop-report.html
