name: StyleCop Analysis for C# Code Quality

on:
  push:
    paths:
      - '**/*.cs'
  pull_request:
    paths:
      - '**/*.cs'
  workflow_dispatch:
    inputs:
      custom_username:
        description: 'Enter custom username (default is "default-user")'
        required: false
        default: 'default-user'
      project_id:
        description: 'Enter project ID (default is "default-project")'
        required: false
        default: 'default-project'

jobs:
  analyze:
    name: Run StyleCop Analysis and Generate Report
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET 9.0.300 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.300'

    - name: Restore Dependencies
      run: |
        PROJECT=$(find . -name "*.csproj" | head -n 1)
        echo "Restoring dependencies for project: $PROJECT"
        dotnet restore "$PROJECT"

    - name: Install StyleCop.Analyzers
      run: |
        PROJECT=$(find . -name "*.csproj" | head -n 1)
        echo "Adding StyleCop.Analyzers to project: $PROJECT"
        dotnet add "$PROJECT" package StyleCop.Analyzers

    - name: Build and Generate StyleCop Output
      run: |
        PROJECT=$(find . -name "*.csproj" | head -n 1)
        echo "Building project: $PROJECT"
        dotnet build "$PROJECT" --configuration Release --no-restore -warnaserror /p:NoWarn=NU1902;NU1903 > build-output.txt 2>&1 || true

    - name: Extract StyleCop Violations
      id: violations
      run: |
        STYLECOP_ERRORS=$(grep -E "(SA[0-9]{4})" build-output.txt | tee stylecop-errors.txt | wc -l)
        echo "StyleCop Violations: $STYLECOP_ERRORS"
        echo "stylecop_violations=$STYLECOP_ERRORS" >> $GITHUB_ENV

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate HTML Report
      run: |
        reportgenerator \
          -reports:build-output.txt \
          -targetdir:report \
          -reporttypes:Html \
          -filefilters:"**/*.cs" || true

    - name: Save Report to docs/ Folder
      run: |
        USERNAME="${{ github.event.inputs.custom_username || 'default-user' }}"
        PROJECT_ID="${{ github.event.inputs.project_id || 'default-project' }}"
        DOCS_FOLDER="docs/${USERNAME}/${PROJECT_ID}/code_quality"
        mkdir -p "$DOCS_FOLDER"
        cp -r report/* "$DOCS_FOLDER/"

    - name: Upload Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: stylecop-report
        path: docs/${{ github.event.inputs.custom_username || 'default-user' }}/**/index.html
