name: Roslyn Analyzers (FxCop) Static Analysis

on:
  push:
    paths:
      - '**/*.cs'
  pull_request:
    paths:
      - '**/*.cs'
  workflow_dispatch:

jobs:
  analyze:
    name: Run Roslyn FxCop Analysis and Generate HTML Report
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Install FxCop Analyzers
      run: |
        PROJECT=$(find . -name "*.csproj" | head -n 1)
        dotnet add "$PROJECT" package Microsoft.CodeAnalysis.FxCopAnalyzers

    - name: Run FxCop Analysis
      run: |
        PROJECT=$(find . -name "*.csproj" | head -n 1)
        dotnet build "$PROJECT" --configuration Release --no-restore -v normal > build-output.xml || true

    - name: Generate HTML Report
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
        reportgenerator -reports:build-output.xml -targetdir:report -reporttypes:Html
        mkdir -p docs/reports
        mv report/* docs/reports/
        
    - name: Upload HTML Report Artifact
      uses: actions/upload-artifact@v2
      with:
        name: fxcop-html-report
        path: docs/reports/
